# Setupss
title:               Jonathan Magee
tagline:             'White Hat Hacker, Beginner, Student.'
description:         'White Hat Hacker, Beginner, Student.'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jonathan Magee
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #G-RE3W5T3R49
