# Setups
title:               Jonathan Magee
tagline:             'White Hat Hacker, beginner, student.'
description:         'White Hat Hacker, beginner, student.'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jonathan Magee
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
